server:
  port: 8888

#app:
#  api-prefix: api/v1

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: identity-service
          uri: lb://identity-service
          predicates:
            - Path=/identity/**
          metadata:
            cors:
              allowedOrigins: "http://localhost:3000"
              allowedMethods: [ "*" ]
              allowedHeaders: [ "*" ]
              allowCredentials: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
